ALL_FILES = ['abalone.arff', 'acute-inflammations.arff', 'ada_agnostic.arff',
       'ada_prior.arff', 'aids.arff', 'ailerons.arff',
       'analcatdata_apnea1.arff', 'analcatdata_apnea2.arff',
       'analcatdata_apnea3.arff', 'analcatdata_asbestos.arff',
       'analcatdata_authorship.arff', 'analcatdata_bankruptcy.arff',
       'analcatdata_birthday.arff', 'analcatdata_bondrate.arff',
       'analcatdata_boxing1.arff', 'analcatdata_boxing2.arff',
       'analcatdata_broadway.arff', 'analcatdata_broadwaymult.arff',
       'analcatdata_challenger.arff', 'analcatdata_chlamydia.arff',
       'analcatdata_creditscore.arff', 'analcatdata_cyyoung8092.arff',
       'analcatdata_cyyoung9302.arff', 'analcatdata_dmft.arff',
       'analcatdata_draft.arff', 'analcatdata_election2000.arff',
       'analcatdata_fraud.arff', 'analcatdata_germangss.arff',
       'analcatdata_gsssexsurvey.arff', 'analcatdata_gviolence.arff',
       'analcatdata_halloffame.arff', 'analcatdata_impeach.arff',
       'analcatdata_japansolvent.arff', 'analcatdata_lawsuit.arff',
       'analcatdata_marketing.arff', 'analcatdata_michiganacc.arff',
       'analcatdata_neavote.arff', 'analcatdata_negotiation.arff',
       'analcatdata_olympic2000.arff', 'analcatdata_reviewer.arff',
       'analcatdata_runshoes.arff', 'analcatdata_seropositive.arff',
       'analcatdata_supreme.arff', 'analcatdata_uktrainacc.arff',
       'analcatdata_vehicle.arff', 'analcatdata_vineyard.arff',
       'analcatdata_whale.arff', 'analcatdata_wildcat.arff', 'anneal.arff',
       'ar1.arff', 'ar3.arff', 'ar4.arff', 'ar5.arff', 'ar6.arff',
       'arrhythmia.arff', 'arsenic-female-bladder.arff',
       'arsenic-female-lung.arff', 'arsenic-male-bladder.arff',
       'arsenic-male-lung.arff', 'audiology.arff', 'Australian.arff',
       'auto93.arff', 'autoHorse.arff', 'autoMpg.arff', 'autoPrice.arff',
       'autos.arff', 'auto_price.arff', 'backache.arff', 'badges2.arff',
       'balance-scale.arff', 'balloon.arff', 'banana.arff',
       'bank-marketing.arff', 'bank32nh.arff', 'bank8FM.arff',
       'baskball.arff', 'biomed.arff',
       'blood-transfusion-service-center.arff', 'bodyfat.arff',
       'bolts.arff', 'boston.arff', 'boston_corrected.arff',
       'braziltourism.arff', 'breast-w.arff', 'breast.arff',
       'breastTumor.arff', 'bridges.arff', 'car.arff', 'CastMetal1.arff',
       'chatfield_4.arff', 'cholesterol.arff', 'chscase_adopt.arff',
       'chscase_census2.arff', 'chscase_census3.arff',
       'chscase_census4.arff', 'chscase_census5.arff',
       'chscase_census6.arff', 'chscase_funds.arff',
       'chscase_geyser1.arff', 'chscase_health.arff', 'chscase_vine1.arff',
       'chscase_vine2.arff', 'chscase_whale.arff', 'churn.arff',
       'clean1.arff', 'clean2.arff', 'cleve.arff', 'cleveland.arff',
       'climate-model-simulation-crashes.arff', 'cloud.arff',
       'cm1_req.arff', 'cmc.arff', 'colleges_aaup.arff', 'collins.arff',
       'confidence.arff', 'corral.arff', 'CostaMadre1.arff', 'cpu.arff',
       'cpu_act.arff', 'cpu_small.arff', 'CreditCardSubset.arff',
       'crx.arff', 'cylinder-bands.arff',
       'dataset_106_molecular-biology_promoters.arff',
       'dataset_13_breast-cancer.arff', 'dataset_24_mushroom.arff',
       'dataset_25_colic.ORIG.arff', 'dataset_27_colic.arff',
       'dataset_29_credit-a.arff', 'dataset_31_credit-g.arff',
       'dataset_37_diabetes.arff', 'dataset_3_kr-vs-kp.arff',
       'dataset_40_sonar.arff', 'dataset_43_haberman.arff',
       'dataset_44_spambase.arff', 'dataset_4_labor.arff',
       'dataset_50_tic-tac-toe.arff', 'dataset_53_heart-statlog.arff',
       'dataset_55_hepatitis.arff', 'dataset_56_vote.arff',
       'dataset_59_ionosphere.arff', 'datatrieve.arff',
       'dbworld-subjects-stemmed.arff', 'dbworld-subjects.arff',
       'delta_ailerons.arff', 'delta_elevators.arff', 'dermatology.arff',
       'diabetes_numeric.arff', 'diggle_table_a1.arff',
       'diggle_table_a2.arff', 'dis.arff', 'disclosure_x_bias.arff',
       'disclosure_x_noise.arff', 'disclosure_x_tampered.arff',
       'disclosure_z.arff', 'dresses-sales.arff', 'echoMonths.arff',
       'ecoli.arff', 'eeg-eye-state.arff', 'elevators.arff',
       'elusage.arff', 'eucalyptus.arff', 'fertility.arff',
       'file2754306a24c0.arff', 'file27543e702e3f.arff',
       'file275449b21aba.arff', 'file275473ee134d.arff',
       'file2754771351f4.arff', 'file2754ffa3f96.arff', 'fishcatch.arff',
       'fl2000.arff', 'flags.arff', 'flare.arff', 'fri_c0_1000_10.arff',
       'fri_c0_1000_25.arff', 'fri_c0_1000_5.arff', 'fri_c0_1000_50.arff',
       'fri_c0_100_10.arff', 'fri_c0_100_25.arff', 'fri_c0_100_5.arff',
       'fri_c0_100_50.arff', 'fri_c0_250_10.arff', 'fri_c0_250_25.arff',
       'fri_c0_250_50.arff', 'fri_c0_500_10.arff', 'fri_c0_500_25.arff',
       'fri_c0_500_5.arff', 'fri_c0_500_50.arff', 'fri_c1_1000_10.arff',
       'fri_c1_1000_25.arff', 'fri_c1_1000_5.arff', 'fri_c1_1000_50.arff',
       'fri_c1_100_10.arff', 'fri_c1_100_25.arff', 'fri_c1_100_5.arff',
       'fri_c1_100_50.arff', 'fri_c1_250_10.arff', 'fri_c1_250_25.arff',
       'fri_c1_250_5.arff', 'fri_c1_250_50.arff', 'fri_c1_500_10.arff',
       'fri_c1_500_25.arff', 'fri_c1_500_5.arff', 'fri_c1_500_50.arff',
       'fri_c2_1000_10.arff', 'fri_c2_1000_25.arff', 'fri_c2_1000_5.arff',
       'fri_c2_1000_50.arff', 'fri_c2_100_10.arff', 'fri_c2_100_25.arff',
       'fri_c2_100_5.arff', 'fri_c2_100_50.arff', 'fri_c2_250_10.arff',
       'fri_c2_250_25.arff', 'fri_c2_250_5.arff', 'fri_c2_250_50.arff',
       'fri_c2_500_10.arff', 'fri_c2_500_25.arff', 'fri_c2_500_5.arff',
       'fri_c2_500_50.arff', 'fri_c3_1000_10.arff', 'fri_c3_1000_25.arff',
       'fri_c3_1000_5.arff', 'fri_c3_1000_50.arff', 'fri_c3_100_10.arff',
       'fri_c3_100_25.arff', 'fri_c3_100_5.arff', 'fri_c3_100_50.arff',
       'fri_c3_250_10.arff', 'fri_c3_250_25.arff', 'fri_c3_250_5.arff',
       'fri_c3_250_50.arff', 'fri_c3_500_10.arff', 'fri_c3_500_25.arff',
       'fri_c3_500_5.arff', 'fri_c3_500_50.arff', 'fri_c4_1000_10.arff',
       'fri_c4_1000_100.arff', 'fri_c4_1000_25.arff',
       'fri_c4_1000_50.arff', 'fri_c4_100_10.arff', 'fri_c4_100_100.arff',
       'fri_c4_100_25.arff', 'fri_c4_100_50.arff', 'fri_c4_250_10.arff',
       'fri_c4_250_100.arff', 'fri_c4_250_25.arff', 'fri_c4_250_50.arff',
       'fri_c4_500_10.arff', 'fri_c4_500_100.arff', 'fri_c4_500_25.arff',
       'fri_c4_500_50.arff', 'fruitfly.arff',
       'GAMETES_Epistasis_2-Way_20atts_0.1H_EDM-1_1.arff',
       'GAMETES_Epistasis_2-Way_20atts_0.4H_EDM-1_1.arff',
       'GAMETES_Epistasis_3-Way_20atts_0.2H_EDM-1_1.arff', 'glass.arff',
       'grub-damage.arff', 'hayes-roth.arff', 'heart-c.arff',
       'heart-h.arff', 'hill-valley.arff', 'hip.arff', 'housing.arff',
       'humandevel.arff', 'hungarian.arff', 'hutsof99_child_witness.arff',
       'hutsof99_logis.arff', 'hypothyroid.arff', 'ilpd.arff', 'iris.arff',
       'irish.arff', 'jEdit_4.0_4.2.arff', 'jEdit_4.2_4.3.arff',
       'jm1.arff', 'kc1-binary.arff', 'kc1-top5.arff', 'kc1.arff',
       'kc2.arff', 'kc3.arff', 'kdd_el_nino-small.arff',
       'kdd_internet_usage.arff', 'kdd_ipums_la_97-small.arff',
       'kdd_ipums_la_98-small.arff', 'kdd_ipums_la_99-small.arff',
       'kdd_JapaneseVowels.arff', 'kdd_synthetic_control.arff',
       'kidney.arff', 'kin8nm.arff', 'KnuggetChase3.arff', 'KungChi3.arff',
       'lowbwt.arff', 'lsvt.arff', 'lungcancer_GSE31210.arff',
       'lupus.arff', 'lymph.arff', 'machine_cpu.arff',
       'MagicTelescope.arff', 'mbagrade.arff', 'mc1.arff', 'mc2.arff',
       'MeanWhile1.arff', 'MegaWatt1.arff', 'meta.arff',
       'mfeat-factors.arff', 'mfeat-fourier.arff', 'mfeat-karhunen.arff',
       'mfeat-morphological.arff', 'mfeat-pixel.arff',
       'mfeat-zernike.arff', 'MindCave2.arff', 'mofn-3-7-10.arff',
       'molecular-biology_promoters.arff', 'monks-problems-1.arff',
       'monks-problems-2.arff', 'monks-problems-3.arff', 'mozilla4.arff',
       'mu284.arff', 'mushroom.arff', 'mux6.arff', 'mw1.arff',
       'newton_hema.arff', 'no2.arff', 'nursery.arff', 'optdigits.arff',
       'ozone-level-8hr.arff', 'page-blocks.arff', 'parity5.arff',
       'parity5_plus_5.arff', 'parkinsons.arff', 'pasture.arff',
       'pbc.arff', 'pbcseq.arff', 'pc1.arff', 'pc1_req.arff', 'pc2.arff',
       'pc3.arff', 'pc4.arff', 'pendigits.arff', 'pharynx.arff',
       'PhishingWebsites.arff', 'phoneme.arff', 'PieChart1.arff',
       'PieChart2.arff', 'PieChart3.arff', 'PieChart4.arff', 'pima.arff',
       'PizzaCutter1.arff', 'PizzaCutter3.arff', 'planning-relax.arff',
       'plasma_retinol.arff', 'pm10.arff', 'pol.arff', 'pollen.arff',
       'pollution.arff', 'postoperative-patient-data.arff',
       'primary-tumor.arff', 'prnn_crabs.arff', 'prnn_fglass.arff',
       'prnn_synth.arff', 'profb.arff', 'puma32H.arff', 'puma8NH.arff',
       'pwLinear.arff', 'pyrim.arff', 'qsar-biodeg.arff', 'quake.arff',
       'qualitative-bankruptcy.arff', 'rabe_131.arff', 'rabe_148.arff',
       'rabe_166.arff', 'rabe_176.arff', 'rabe_265.arff', 'rabe_266.arff',
       'rabe_97.arff', 'ringnorm.arff', 'rmftsa_ctoarrivals.arff',
       'rmftsa_ladata.arff', 'rmftsa_sleepdata.arff', 'sa-heart.arff',
       'scene.arff', 'schizo.arff', 'schlvote.arff', 'segment.arff',
       'sensory.arff', 'servo.arff', 'sleep.arff', 'sleuth_case1102.arff',
       'sleuth_case1201.arff', 'sleuth_case1202.arff',
       'sleuth_case2002.arff', 'sleuth_ex1221.arff', 'sleuth_ex1605.arff',
       'sleuth_ex1714.arff', 'sleuth_ex2015.arff', 'sleuth_ex2016.arff',
       'socmob.arff', 'soybean.arff', 'space_ga.arff', 'SPECT.arff',
       'SPECTF.arff', 'spectrometer.arff', 'speeddating.arff',
       'sponge.arff', 'squash-stored.arff', 'squash-unstored.arff',
       'steel-plates-fault.arff', 'stock.arff', 'strikes.arff',
       'sylva_agnostic.arff', 'sylva_prior.arff', 'tae.arff',
       'tecator.arff', 'thoracic-surgery.arff', 'thoracic_surgery.arff',
       'threeOf9.arff', 'titanic.arff', 'tokyo1.arff', 'transplant.arff',
       'triazines.arff', 'twonorm.arff', 'vehicle.arff',
       'vertebra-column.arff', 'veteran.arff', 'vineyard.arff',
       'vinnie.arff', 'visualizing_environmental.arff',
       'visualizing_ethanol.arff', 'visualizing_galaxy.arff',
       'visualizing_hamster.arff', 'visualizing_livestock.arff',
       'visualizing_slope.arff', 'visualizing_soil.arff', 'vowel.arff',
       'water-treatment.arff', 'waveform-5000.arff', 'wdbc.arff',
       'white-clover.arff', 'wholesale-customers.arff', 'wilt.arff',
       'wind.arff', 'wind_correlations.arff', 'wine.arff',
       'wisconsin.arff', 'witmer_census_1980.arff', 'xd6.arff',
       'yeast_ml8.arff', 'zoo.arff']