from hyperopt import hp

ALL_FILES = ['abalone.arff', 'acute-inflammations.arff', 'ada_agnostic.arff',
       'ada_prior.arff', 'aids.arff', 'ailerons.arff',
       'analcatdata_apnea1.arff', 'analcatdata_apnea2.arff',
       'analcatdata_apnea3.arff', 'analcatdata_asbestos.arff',
       'analcatdata_authorship.arff', 'analcatdata_bankruptcy.arff',
       'analcatdata_birthday.arff', 'analcatdata_bondrate.arff',
       'analcatdata_boxing1.arff', 'analcatdata_boxing2.arff',
       'analcatdata_broadway.arff', 'analcatdata_broadwaymult.arff',
       'analcatdata_challenger.arff', 'analcatdata_chlamydia.arff',
       'analcatdata_creditscore.arff', 'analcatdata_cyyoung8092.arff',
       'analcatdata_cyyoung9302.arff', 'analcatdata_dmft.arff',
       'analcatdata_draft.arff', 'analcatdata_election2000.arff',
       'analcatdata_fraud.arff', 'analcatdata_germangss.arff',
       'analcatdata_gsssexsurvey.arff', 'analcatdata_gviolence.arff',
       'analcatdata_halloffame.arff', 'analcatdata_impeach.arff',
       'analcatdata_japansolvent.arff', 'analcatdata_lawsuit.arff',
       'analcatdata_marketing.arff', 'analcatdata_michiganacc.arff',
       'analcatdata_neavote.arff', 'analcatdata_negotiation.arff',
       'analcatdata_olympic2000.arff', 'analcatdata_reviewer.arff',
       'analcatdata_runshoes.arff', 'analcatdata_seropositive.arff',
       'analcatdata_supreme.arff', 'analcatdata_uktrainacc.arff',
       'analcatdata_vehicle.arff', 'analcatdata_vineyard.arff',
       'analcatdata_whale.arff', 'analcatdata_wildcat.arff', 'anneal.arff',
       'ar1.arff', 'ar3.arff', 'ar4.arff', 'ar5.arff', 'ar6.arff',
       'arrhythmia.arff', 'arsenic-female-bladder.arff',
       'arsenic-female-lung.arff', 'arsenic-male-bladder.arff',
       'arsenic-male-lung.arff', 'audiology.arff', 'Australian.arff',
       'auto93.arff', 'autoHorse.arff', 'autoMpg.arff', 'autoPrice.arff',
       'autos.arff', 'autoUniv-au1-1000.arff', 'auto_price.arff',
       'backache.arff', 'badges2.arff', 'balance-scale.arff',
       'balloon.arff', 'banana.arff', 'bank-marketing.arff',
       'bank32nh.arff', 'bank8FM.arff', 'banknote-authentication.arff',
       'baskball.arff', 'biomed.arff', 'blogger.arff',
       'blood-transfusion-service-center.arff', 'bodyfat.arff',
       'bolts.arff', 'boston.arff', 'boston_corrected.arff',
       'braziltourism.arff', 'breast-w.arff', 'breast.arff',
       'breastTumor.arff', 'bridges.arff', 'car.arff', 'cars.arff',
       'CastMetal1.arff', 'chatfield_4.arff', 'cholesterol.arff',
       'chscase_adopt.arff', 'chscase_census2.arff',
       'chscase_census3.arff', 'chscase_census4.arff',
       'chscase_census5.arff', 'chscase_census6.arff',
       'chscase_funds.arff', 'chscase_geyser1.arff', 'chscase_health.arff',
       'chscase_vine1.arff', 'chscase_vine2.arff', 'chscase_whale.arff',
       'churn.arff', 'clean1.arff', 'clean2.arff', 'cleve.arff',
       'cleveland.arff', 'climate-model-simulation-crashes.arff',
       'cloud.arff', 'cm1_req.arff', 'cmc.arff', 'colleges_aaup.arff',
       'colleges_usnews.arff', 'collins.arff', 'confidence.arff',
       'corral.arff', 'CostaMadre1.arff', 'cpu.arff', 'cpu_act.arff',
       'cpu_small.arff', 'CreditCardSubset.arff', 'crx.arff',
       'cylinder-bands.arff',
       'dataset_106_molecular-biology_promoters.arff',
       'dataset_114_shuttle-landing-control.arff',
       'dataset_13_breast-cancer.arff', 'dataset_24_mushroom.arff',
       'dataset_25_colic.ORIG.arff', 'dataset_27_colic.arff',
       'dataset_29_credit-a.arff', 'dataset_31_credit-g.arff',
       'dataset_37_diabetes.arff', 'dataset_38_sick.arff',
       'dataset_3_kr-vs-kp.arff', 'dataset_40_sonar.arff',
       'dataset_43_haberman.arff', 'dataset_44_spambase.arff',
       'dataset_4_labor.arff', 'dataset_50_tic-tac-toe.arff',
       'dataset_52_trains.arff', 'dataset_53_heart-statlog.arff',
       'dataset_55_hepatitis.arff', 'dataset_56_vote.arff',
       'dataset_59_ionosphere.arff', 'datatrieve.arff',
       'dbworld-subjects-stemmed.arff', 'dbworld-subjects.arff',
       'delta_ailerons.arff', 'delta_elevators.arff', 'dermatology.arff',
       'diabetes_numeric.arff', 'diggle_table_a1.arff',
       'diggle_table_a2.arff', 'dis.arff', 'disclosure_x_bias.arff',
       'disclosure_x_noise.arff', 'disclosure_x_tampered.arff',
       'disclosure_z.arff', 'dresses-sales.arff', 'echoMonths.arff',
       'ecoli.arff', 'eeg-eye-state.arff', 'elevators.arff',
       'elusage.arff', 'eucalyptus.arff', 'fertility.arff',
       'file2754306a24c0.arff', 'file27543e702e3f.arff',
       'file275449b21aba.arff', 'file275473ee134d.arff',
       'file2754771351f4.arff', 'file2754ffa3f96.arff', 'fishcatch.arff',
       'fl2000.arff', 'flags.arff', 'flare.arff', 'fri_c0_1000_10.arff',
       'fri_c0_1000_25.arff', 'fri_c0_1000_5.arff', 'fri_c0_1000_50.arff',
       'fri_c0_100_10.arff', 'fri_c0_100_25.arff', 'fri_c0_100_5.arff',
       'fri_c0_100_50.arff', 'fri_c0_250_10.arff', 'fri_c0_250_25.arff',
       'fri_c0_250_50.arff', 'fri_c0_500_10.arff', 'fri_c0_500_25.arff',
       'fri_c0_500_5.arff', 'fri_c0_500_50.arff', 'fri_c1_1000_10.arff',
       'fri_c1_1000_25.arff', 'fri_c1_1000_5.arff', 'fri_c1_1000_50.arff',
       'fri_c1_100_10.arff', 'fri_c1_100_25.arff', 'fri_c1_100_5.arff',
       'fri_c1_100_50.arff', 'fri_c1_250_10.arff', 'fri_c1_250_25.arff',
       'fri_c1_250_5.arff', 'fri_c1_250_50.arff', 'fri_c1_500_10.arff',
       'fri_c1_500_25.arff', 'fri_c1_500_5.arff', 'fri_c1_500_50.arff',
       'fri_c2_1000_10.arff', 'fri_c2_1000_25.arff', 'fri_c2_1000_5.arff',
       'fri_c2_1000_50.arff', 'fri_c2_100_10.arff', 'fri_c2_100_25.arff',
       'fri_c2_100_5.arff', 'fri_c2_100_50.arff', 'fri_c2_250_10.arff',
       'fri_c2_250_25.arff', 'fri_c2_250_5.arff', 'fri_c2_250_50.arff',
       'fri_c2_500_10.arff', 'fri_c2_500_25.arff', 'fri_c2_500_5.arff',
       'fri_c2_500_50.arff', 'fri_c3_1000_10.arff', 'fri_c3_1000_25.arff',
       'fri_c3_1000_5.arff', 'fri_c3_1000_50.arff', 'fri_c3_100_10.arff',
       'fri_c3_100_25.arff', 'fri_c3_100_5.arff', 'fri_c3_100_50.arff',
       'fri_c3_250_10.arff', 'fri_c3_250_25.arff', 'fri_c3_250_5.arff',
       'fri_c3_250_50.arff', 'fri_c3_500_10.arff', 'fri_c3_500_25.arff',
       'fri_c3_500_5.arff', 'fri_c3_500_50.arff', 'fri_c4_1000_10.arff',
       'fri_c4_1000_100.arff', 'fri_c4_1000_25.arff',
       'fri_c4_1000_50.arff', 'fri_c4_100_10.arff', 'fri_c4_100_100.arff',
       'fri_c4_100_25.arff', 'fri_c4_100_50.arff', 'fri_c4_250_10.arff',
       'fri_c4_250_100.arff', 'fri_c4_250_25.arff', 'fri_c4_250_50.arff',
       'fri_c4_500_10.arff', 'fri_c4_500_100.arff', 'fri_c4_500_25.arff',
       'fri_c4_500_50.arff', 'fruitfly.arff',
       'GAMETES_Epistasis_2-Way_20atts_0.1H_EDM-1_1.arff',
       'GAMETES_Epistasis_2-Way_20atts_0.4H_EDM-1_1.arff',
       'GAMETES_Epistasis_3-Way_20atts_0.2H_EDM-1_1.arff', 'glass.arff',
       'grub-damage.arff', 'hayes-roth.arff', 'heart-c.arff',
       'heart-h.arff', 'hill-valley.arff', 'hip.arff', 'housing.arff',
       'humandevel.arff', 'hungarian.arff', 'hutsof99_child_witness.arff',
       'hutsof99_logis.arff', 'hypothyroid.arff', 'ilpd.arff', 'iris.arff',
       'irish.arff', 'jEdit_4.0_4.2.arff', 'jEdit_4.2_4.3.arff',
       'jm1.arff', 'kc1-binary.arff', 'kc1-top5.arff', 'kc1.arff',
       'kc2.arff', 'kc3.arff', 'kdd_el_nino-small.arff',
       'kdd_internet_usage.arff', 'kdd_ipums_la_97-small.arff',
       'kdd_ipums_la_98-small.arff', 'kdd_ipums_la_99-small.arff',
       'kdd_JapaneseVowels.arff', 'kdd_synthetic_control.arff',
       'kidney.arff', 'kin8nm.arff', 'KnuggetChase3.arff', 'KungChi3.arff',
       'lowbwt.arff', 'lsvt.arff', 'lungcancer_GSE31210.arff',
       'lupus.arff', 'lymph.arff', 'machine_cpu.arff',
       'MagicTelescope.arff', 'mammography.arff', 'mbagrade.arff',
       'mc1.arff', 'mc2.arff', 'MeanWhile1.arff', 'MegaWatt1.arff',
       'meta.arff', 'mfeat-factors.arff', 'mfeat-fourier.arff',
       'mfeat-karhunen.arff', 'mfeat-morphological.arff',
       'mfeat-pixel.arff', 'mfeat-zernike.arff', 'MindCave2.arff',
       'mofn-3-7-10.arff', 'molecular-biology_promoters.arff',
       'monks-problems-1.arff', 'monks-problems-2.arff',
       'monks-problems-3.arff', 'mozilla4.arff', 'mu284.arff',
       'mushroom.arff', 'musk.arff', 'mux6.arff', 'mw1.arff',
       'newton_hema.arff', 'no2.arff', 'nursery.arff', 'oil_spill.arff',
       'optdigits.arff', 'ozone-level-8hr.arff', 'page-blocks.arff',
       'parity5.arff', 'parity5_plus_5.arff', 'parkinsons.arff',
       'pasture.arff', 'pbc.arff', 'pbcseq.arff', 'pc1.arff',
       'pc1_req.arff', 'pc2.arff', 'pc3.arff', 'pc4.arff',
       'pendigits.arff', 'pharynx.arff', 'PhishingWebsites.arff',
       'phoneme.arff', 'PieChart1.arff', 'PieChart2.arff',
       'PieChart3.arff', 'PieChart4.arff', 'pima.arff',
       'PizzaCutter1.arff', 'PizzaCutter3.arff', 'planning-relax.arff',
       'plasma_retinol.arff', 'pm10.arff', 'pol.arff', 'pollen.arff',
       'pollution.arff', 'postoperative-patient-data.arff',
       'primary-tumor.arff', 'prnn_crabs.arff', 'prnn_fglass.arff',
       'prnn_synth.arff', 'profb.arff', 'puma32H.arff', 'puma8NH.arff',
       'pwLinear.arff', 'pyrim.arff', 'qsar-biodeg.arff', 'quake.arff',
       'qualitative-bankruptcy.arff', 'rabe_131.arff', 'rabe_148.arff',
       'rabe_166.arff', 'rabe_176.arff', 'rabe_265.arff', 'rabe_266.arff',
       'rabe_97.arff', 'ringnorm.arff', 'rmftsa_ctoarrivals.arff',
       'rmftsa_ladata.arff', 'rmftsa_sleepdata.arff', 'sa-heart.arff',
       'scene.arff', 'schizo.arff', 'schlvote.arff', 'segment.arff',
       'sensory.arff', 'servo.arff', 'sleep.arff', 'sleuth_case1102.arff',
       'sleuth_case1201.arff', 'sleuth_case1202.arff',
       'sleuth_case2002.arff', 'sleuth_ex1221.arff', 'sleuth_ex1605.arff',
       'sleuth_ex1714.arff', 'sleuth_ex2015.arff', 'sleuth_ex2016.arff',
       'socmob.arff', 'soybean.arff', 'space_ga.arff', 'SPECT.arff',
       'SPECTF.arff', 'spectrometer.arff', 'speeddating.arff',
       'splice.arff', 'sponge.arff', 'squash-stored.arff',
       'squash-unstored.arff', 'steel-plates-fault.arff', 'stock.arff',
       'strikes.arff', 'sylva_agnostic.arff', 'sylva_prior.arff',
       'SyskillWebert-Sheep.arff', 'tae.arff', 'tecator.arff',
       'thoracic-surgery.arff', 'thoracic_surgery.arff', 'threeOf9.arff',
       'titanic.arff', 'tokyo1.arff', 'transplant.arff', 'triazines.arff',
       'twonorm.arff', 'vehicle.arff', 'vertebra-column.arff',
       'veteran.arff', 'vineyard.arff', 'vinnie.arff',
       'visualizing_environmental.arff', 'visualizing_ethanol.arff',
       'visualizing_galaxy.arff', 'visualizing_hamster.arff',
       'visualizing_livestock.arff', 'visualizing_slope.arff',
       'visualizing_soil.arff', 'vowel.arff', 'water-treatment.arff',
       'waveform-5000.arff', 'wdbc.arff', 'white-clover.arff',
       'wholesale-customers.arff', 'wilt.arff', 'wind.arff',
       'wind_correlations.arff', 'wine.arff', 'wisconsin.arff',
       'witmer_census_1980.arff', 'xd6.arff', 'yeast_ml8.arff', 'zoo.arff']

COMPUTED_FILES = ['abalone.txt', 'acute-inflammations.txt', 'ada_agnostic.txt',
       'ada_prior.txt', 'aids.txt', 'ailerons.txt',
       'analcatdata_apnea1.txt', 'analcatdata_apnea2.txt',
       'analcatdata_apnea3.txt', 'analcatdata_asbestos.txt',
       'analcatdata_authorship.txt', 'analcatdata_bankruptcy.txt',
       'analcatdata_birthday.txt', 'analcatdata_bondrate.txt',
       'analcatdata_boxing1.txt', 'analcatdata_boxing2.txt',
       'analcatdata_broadway.txt', 'analcatdata_broadwaymult.txt',
       'analcatdata_challenger.txt', 'analcatdata_chlamydia.txt',
       'analcatdata_creditscore.txt', 'analcatdata_cyyoung8092.txt',
       'analcatdata_cyyoung9302.txt', 'analcatdata_dmft.txt',
       'analcatdata_draft.txt', 'analcatdata_election2000.txt',
       'analcatdata_fraud.txt', 'analcatdata_germangss.txt',
       'analcatdata_gsssexsurvey.txt', 'analcatdata_gviolence.txt',
       'analcatdata_halloffame.txt', 'analcatdata_impeach.txt',
       'analcatdata_japansolvent.txt', 'analcatdata_lawsuit.txt',
       'analcatdata_marketing.txt', 'analcatdata_michiganacc.txt',
       'analcatdata_neavote.txt', 'analcatdata_negotiation.txt',
       'analcatdata_olympic2000.txt', 'analcatdata_reviewer.txt',
       'analcatdata_runshoes.txt', 'analcatdata_seropositive.txt',
       'analcatdata_supreme.txt', 'analcatdata_uktrainacc.txt',
       'analcatdata_vehicle.txt', 'analcatdata_vineyard.txt',
       'analcatdata_whale.txt', 'analcatdata_wildcat.txt', 'anneal.txt',
       'ar1.txt', 'ar3.txt', 'ar4.txt', 'ar5.txt', 'ar6.txt',
       'arrhythmia.txt', 'arsenic-female-bladder.txt',
       'arsenic-female-lung.txt', 'arsenic-male-bladder.txt',
       'arsenic-male-lung.txt', 'audiology.txt', 'Australian.txt',
       'auto93.txt', 'autoHorse.txt', 'autoMpg.txt', 'autoPrice.txt',
       'autos.txt', 'auto_price.txt', 'backache.txt', 'badges2.txt',
       'balance-scale.txt', 'balloon.txt', 'banana.txt',
       'bank-marketing.txt', 'bank32nh.txt', 'bank8FM.txt', 'baskball.txt',
       'biomed.txt', 'blood-transfusion-service-center.txt', 'bodyfat.txt',
       'bolts.txt', 'boston.txt', 'boston_corrected.txt',
       'braziltourism.txt', 'breast-w.txt', 'breast.txt',
       'breastTumor.txt', 'bridges.txt', 'car.txt', 'cars.txt',
       'CastMetal1.txt', 'chatfield_4.txt', 'cholesterol.txt',
       'chscase_adopt.txt', 'chscase_census2.txt', 'chscase_census3.txt',
       'chscase_census4.txt', 'chscase_census5.txt', 'chscase_census6.txt',
       'chscase_funds.txt', 'chscase_geyser1.txt', 'chscase_health.txt',
       'chscase_vine1.txt', 'chscase_vine2.txt', 'chscase_whale.txt',
       'churn.txt', 'clean1.txt', 'clean2.txt', 'cleve.txt',
       'cleveland.txt', 'climate-model-simulation-crashes.txt',
       'cloud.txt', 'cm1_req.txt', 'cmc.txt', 'colleges_aaup.txt',
       'colleges_usnews.txt', 'collins.txt', 'confidence.txt',
       'corral.txt', 'CostaMadre1.txt', 'cpu.txt', 'cpu_act.txt',
       'cpu_small.txt', 'CreditCardSubset.txt', 'crx.txt',
       'cylinder-bands.txt', 'dataset_106_molecular-biology_promoters.txt',
       'dataset_13_breast-cancer.txt', 'dataset_24_mushroom.txt',
       'dataset_25_colic.ORIG.txt', 'dataset_27_colic.txt',
       'dataset_29_credit-a.txt', 'dataset_31_credit-g.txt',
       'dataset_37_diabetes.txt', 'dataset_38_sick.txt',
       'dataset_3_kr-vs-kp.txt', 'dataset_40_sonar.txt',
       'dataset_43_haberman.txt', 'dataset_44_spambase.txt',
       'dataset_4_labor.txt', 'dataset_50_tic-tac-toe.txt',
       'dataset_53_heart-statlog.txt', 'dataset_55_hepatitis.txt',
       'dataset_56_vote.txt', 'dataset_59_ionosphere.txt',
       'datatrieve.txt', 'dbworld-subjects-stemmed.txt',
       'dbworld-subjects.txt', 'delta_ailerons.txt', 'delta_elevators.txt',
       'dermatology.txt', 'diabetes_numeric.txt', 'diggle_table_a1.txt',
       'diggle_table_a2.txt', 'dis.txt', 'disclosure_x_bias.txt',
       'disclosure_x_noise.txt', 'disclosure_x_tampered.txt',
       'disclosure_z.txt', 'dresses-sales.txt', 'echoMonths.txt',
       'ecoli.txt', 'eeg-eye-state.txt', 'elevators.txt', 'elusage.txt',
       'eucalyptus.txt', 'fertility.txt', 'file2754306a24c0.txt',
       'file27543e702e3f.txt', 'file275449b21aba.txt',
       'file275473ee134d.txt', 'file2754771351f4.txt',
       'file2754ffa3f96.txt', 'fishcatch.txt', 'fl2000.txt', 'flags.txt',
       'flare.txt', 'fri_c0_1000_10.txt', 'fri_c0_1000_25.txt',
       'fri_c0_1000_5.txt', 'fri_c0_1000_50.txt', 'fri_c0_100_10.txt',
       'fri_c0_100_25.txt', 'fri_c0_100_5.txt', 'fri_c0_100_50.txt',
       'fri_c0_250_10.txt', 'fri_c0_250_25.txt', 'fri_c0_250_50.txt',
       'fri_c0_500_10.txt', 'fri_c0_500_25.txt', 'fri_c0_500_5.txt',
       'fri_c0_500_50.txt', 'fri_c1_1000_10.txt', 'fri_c1_1000_25.txt',
       'fri_c1_1000_5.txt', 'fri_c1_1000_50.txt', 'fri_c1_100_10.txt',
       'fri_c1_100_25.txt', 'fri_c1_100_5.txt', 'fri_c1_100_50.txt',
       'fri_c1_250_10.txt', 'fri_c1_250_25.txt', 'fri_c1_250_5.txt',
       'fri_c1_250_50.txt', 'fri_c1_500_10.txt', 'fri_c1_500_25.txt',
       'fri_c1_500_5.txt', 'fri_c1_500_50.txt', 'fri_c2_1000_10.txt',
       'fri_c2_1000_25.txt', 'fri_c2_1000_5.txt', 'fri_c2_1000_50.txt',
       'fri_c2_100_10.txt', 'fri_c2_100_25.txt', 'fri_c2_100_5.txt',
       'fri_c2_100_50.txt', 'fri_c2_250_10.txt', 'fri_c2_250_25.txt',
       'fri_c2_250_5.txt', 'fri_c2_250_50.txt', 'fri_c2_500_10.txt',
       'fri_c2_500_25.txt', 'fri_c2_500_5.txt', 'fri_c2_500_50.txt',
       'fri_c3_1000_10.txt', 'fri_c3_1000_25.txt', 'fri_c3_1000_5.txt',
       'fri_c3_1000_50.txt', 'fri_c3_100_10.txt', 'fri_c3_100_25.txt',
       'fri_c3_100_5.txt', 'fri_c3_100_50.txt', 'fri_c3_250_10.txt',
       'fri_c3_250_25.txt', 'fri_c3_250_5.txt', 'fri_c3_250_50.txt',
       'fri_c3_500_10.txt', 'fri_c3_500_25.txt', 'fri_c3_500_5.txt',
       'fri_c3_500_50.txt', 'fri_c4_1000_10.txt', 'fri_c4_1000_100.txt',
       'fri_c4_1000_25.txt', 'fri_c4_1000_50.txt', 'fri_c4_100_10.txt',
       'fri_c4_100_100.txt', 'fri_c4_100_25.txt', 'fri_c4_100_50.txt',
       'fri_c4_250_10.txt', 'fri_c4_250_100.txt', 'fri_c4_250_25.txt',
       'fri_c4_250_50.txt', 'fri_c4_500_10.txt', 'fri_c4_500_100.txt',
       'fri_c4_500_25.txt', 'fri_c4_500_50.txt', 'fruitfly.txt',
       'GAMETES_Epistasis_2-Way_20atts_0.1H_EDM-1_1.txt',
       'GAMETES_Epistasis_2-Way_20atts_0.4H_EDM-1_1.txt',
       'GAMETES_Epistasis_3-Way_20atts_0.2H_EDM-1_1.txt', 'glass.txt',
       'grub-damage.txt', 'hayes-roth.txt', 'heart-c.txt', 'heart-h.txt',
       'hill-valley.txt', 'hip.txt', 'housing.txt', 'humandevel.txt',
       'hungarian.txt', 'hutsof99_child_witness.txt', 'hutsof99_logis.txt',
       'hypothyroid.txt', 'ilpd.txt', 'iris.txt', 'irish.txt',
       'jEdit_4.0_4.2.txt', 'jEdit_4.2_4.3.txt', 'jm1.txt',
       'kc1-binary.txt', 'kc1-top5.txt', 'kc1.txt', 'kc2.txt', 'kc3.txt',
       'kdd_el_nino-small.txt', 'kdd_internet_usage.txt',
       'kdd_ipums_la_99-small.txt', 'kdd_JapaneseVowels.txt',
       'kdd_synthetic_control.txt', 'kidney.txt', 'kin8nm.txt',
       'KnuggetChase3.txt', 'KungChi3.txt', 'lowbwt.txt', 'lsvt.txt',
       'lungcancer_GSE31210.txt', 'lupus.txt', 'lymph.txt',
       'machine_cpu.txt', 'MagicTelescope.txt', 'mbagrade.txt', 'mc1.txt',
       'mc2.txt', 'MeanWhile1.txt', 'MegaWatt1.txt', 'meta.txt',
       'mfeat-factors.txt', 'mfeat-fourier.txt', 'mfeat-karhunen.txt',
       'mfeat-morphological.txt', 'mfeat-pixel.txt', 'mfeat-zernike.txt',
       'MindCave2.txt', 'mofn-3-7-10.txt',
       'molecular-biology_promoters.txt', 'monks-problems-1.txt',
       'monks-problems-2.txt', 'monks-problems-3.txt', 'mozilla4.txt',
       'mu284.txt', 'mushroom.txt', 'musk.txt', 'mux6.txt', 'mw1.txt',
       'newton_hema.txt', 'no2.txt', 'nursery.txt', 'optdigits.txt',
       'ozone-level-8hr.txt', 'page-blocks.txt', 'parity5.txt',
       'parity5_plus_5.txt', 'parkinsons.txt', 'pasture.txt', 'pbc.txt',
       'pbcseq.txt', 'pc1.txt', 'pc1_req.txt', 'pc2.txt', 'pc3.txt',
       'pc4.txt', 'pendigits.txt', 'pharynx.txt', 'PhishingWebsites.txt',
       'phoneme.txt', 'PieChart1.txt', 'PieChart2.txt', 'PieChart3.txt',
       'PieChart4.txt', 'pima.txt', 'PizzaCutter1.txt', 'PizzaCutter3.txt',
       'planning-relax.txt', 'plasma_retinol.txt', 'pm10.txt', 'pol.txt',
       'pollen.txt', 'pollution.txt', 'postoperative-patient-data.txt',
       'primary-tumor.txt', 'prnn_crabs.txt', 'prnn_fglass.txt',
       'prnn_synth.txt', 'profb.txt', 'puma32H.txt', 'puma8NH.txt',
       'pwLinear.txt', 'pyrim.txt', 'qsar-biodeg.txt', 'quake.txt',
       'qualitative-bankruptcy.txt', 'rabe_131.txt', 'rabe_148.txt',
       'rabe_166.txt', 'rabe_176.txt', 'rabe_265.txt', 'rabe_266.txt',
       'rabe_97.txt', 'ringnorm.txt', 'rmftsa_ctoarrivals.txt',
       'rmftsa_ladata.txt', 'rmftsa_sleepdata.txt', 'sa-heart.txt',
       'scene.txt', 'schizo.txt', 'schlvote.txt', 'segment.txt',
       'sensory.txt', 'servo.txt', 'sleep.txt', 'sleuth_case1102.txt',
       'sleuth_case1201.txt', 'sleuth_case1202.txt', 'sleuth_case2002.txt',
       'sleuth_ex1221.txt', 'sleuth_ex1605.txt', 'sleuth_ex1714.txt',
       'sleuth_ex2015.txt', 'sleuth_ex2016.txt', 'socmob.txt',
       'soybean.txt', 'space_ga.txt', 'SPECT.txt', 'SPECTF.txt',
       'spectrometer.txt', 'speeddating.txt', 'splice.txt', 'sponge.txt',
       'squash-stored.txt', 'squash-unstored.txt',
       'steel-plates-fault.txt', 'stock.txt', 'strikes.txt',
       'sylva_agnostic.txt', 'sylva_prior.txt', 'tae.txt', 'tecator.txt',
       'thoracic-surgery.txt', 'thoracic_surgery.txt', 'threeOf9.txt',
       'titanic.txt', 'tokyo1.txt', 'transplant.txt', 'triazines.txt',
       'twonorm.txt', 'vehicle.txt', 'vertebra-column.txt', 'veteran.txt',
       'vineyard.txt', 'vinnie.txt', 'visualizing_environmental.txt',
       'visualizing_ethanol.txt', 'visualizing_galaxy.txt',
       'visualizing_hamster.txt', 'visualizing_livestock.txt',
       'visualizing_slope.txt', 'visualizing_soil.txt', 'vowel.txt',
       'water-treatment.txt', 'waveform-5000.txt', 'wdbc.txt',
       'white-clover.txt', 'wilt.txt', 'wind.txt', 'wind_correlations.txt',
       'wine.txt', 'wisconsin.txt', 'witmer_census_1980.txt', 'xd6.txt',
       'yeast_ml8.txt', 'zoo.txt']

COMPUTED_FILES_CAT = ['abalone.txt', 'acute-inflammations.txt', 'ada_agnostic.txt',
       'ada_prior.txt', 'aids.txt', 'ailerons.txt',
       'analcatdata_apnea1.txt', 'analcatdata_apnea2.txt',
       'analcatdata_apnea3.txt', 'analcatdata_asbestos.txt',
       'analcatdata_authorship.txt', 'analcatdata_bankruptcy.txt',
       'analcatdata_birthday.txt', 'analcatdata_bondrate.txt',
       'analcatdata_boxing1.txt', 'analcatdata_boxing2.txt',
       'analcatdata_broadway.txt', 'analcatdata_broadwaymult.txt',
       'analcatdata_challenger.txt', 'analcatdata_chlamydia.txt',
       'analcatdata_creditscore.txt', 'analcatdata_cyyoung8092.txt',
       'analcatdata_cyyoung9302.txt', 'analcatdata_dmft.txt',
       'analcatdata_draft.txt', 'analcatdata_election2000.txt',
       'analcatdata_fraud.txt', 'analcatdata_germangss.txt',
       'analcatdata_gsssexsurvey.txt', 'analcatdata_gviolence.txt',
       'analcatdata_halloffame.txt', 'analcatdata_impeach.txt',
       'analcatdata_japansolvent.txt', 'analcatdata_lawsuit.txt',
       'analcatdata_marketing.txt', 'analcatdata_michiganacc.txt',
       'analcatdata_neavote.txt', 'analcatdata_negotiation.txt',
       'analcatdata_olympic2000.txt', 'analcatdata_reviewer.txt',
       'analcatdata_runshoes.txt', 'analcatdata_seropositive.txt',
       'analcatdata_supreme.txt', 'analcatdata_uktrainacc.txt',
       'analcatdata_vehicle.txt', 'analcatdata_vineyard.txt',
       'analcatdata_whale.txt', 'analcatdata_wildcat.txt', 'anneal.txt',
       'ar1.txt', 'ar3.txt', 'ar4.txt', 'ar5.txt', 'ar6.txt',
       'arrhythmia.txt', 'arsenic-female-bladder.txt',
       'arsenic-female-lung.txt', 'arsenic-male-bladder.txt',
       'arsenic-male-lung.txt', 'audiology.txt', 'Australian.txt',
       'auto93.txt', 'autoHorse.txt', 'autoMpg.txt', 'autoPrice.txt',
       'autos.txt', 'auto_price.txt', 'backache.txt', 'badges2.txt',
       'balance-scale.txt', 'balloon.txt', 'banana.txt',
       'bank-marketing.txt', 'bank32nh.txt', 'bank8FM.txt', 'baskball.txt',
       'biomed.txt', 'blood-transfusion-service-center.txt', 'bodyfat.txt',
       'bolts.txt', 'boston.txt', 'chscase_census6.txt',
       'chscase_funds.txt', 'chscase_geyser1.txt', 'chscase_health.txt',
       'chscase_vine1.txt', 'chscase_vine2.txt', 'chscase_whale.txt',
       'churn.txt', 'clean1.txt', 'clean2.txt', 'cleve.txt',
       'cleveland.txt', 'climate-model-simulation-crashes.txt',
       'cloud.txt', 'cm1_req.txt', 'cmc.txt', 'colleges_aaup.txt',
       'colleges_usnews.txt', 'collins.txt', 'confidence.txt',
       'corral.txt', 'CostaMadre1.txt', 'cpu.txt', 'cpu_act.txt',
       'cpu_small.txt', 'CreditCardSubset.txt', 'crx.txt',
       'cylinder-bands.txt', 'dataset_106_molecular-biology_promoters.txt',
       'dataset_114_shuttle-landing-control.txt',
       'dataset_13_breast-cancer.txt', 'dataset_24_mushroom.txt',
       'dataset_25_colic.ORIG.txt', 'dataset_27_colic.txt',
       'dataset_29_credit-a.txt', 'dataset_31_credit-g.txt',
       'dataset_37_diabetes.txt', 'dataset_38_sick.txt',
       'dataset_3_kr-vs-kp.txt', 'dataset_40_sonar.txt',
       'dataset_43_haberman.txt', 'dataset_44_spambase.txt',
       'dataset_4_labor.txt', 'dataset_50_tic-tac-toe.txt',
       'dataset_52_trains.txt', 'dataset_53_heart-statlog.txt',
       'dataset_55_hepatitis.txt', 'dataset_56_vote.txt',
       'dataset_59_ionosphere.txt', 'datatrieve.txt',
       'dbworld-subjects-stemmed.txt', 'dbworld-subjects.txt',
       'delta_ailerons.txt', 'delta_elevators.txt', 'dermatology.txt',
       'diabetes_numeric.txt', 'diggle_table_a1.txt',
       'diggle_table_a2.txt', 'dis.txt', 'disclosure_x_bias.txt',
       'disclosure_x_noise.txt', 'disclosure_x_tampered.txt',
       'disclosure_z.txt', 'dresses-sales.txt', 'echoMonths.txt',
       'ecoli.txt', 'eeg-eye-state.txt', 'elevators.txt', 'elusage.txt',
       'eucalyptus.txt', 'fertility.txt', 'file2754306a24c0.txt',
       'file27543e702e3f.txt', 'file275449b21aba.txt',
       'file275473ee134d.txt', 'file2754771351f4.txt',
       'file2754ffa3f96.txt', 'fishcatch.txt', 'fl2000.txt', 'flags.txt',
       'flare.txt', 'fri_c0_1000_10.txt', 'fri_c0_1000_25.txt',
       'fri_c0_1000_5.txt', 'fri_c0_1000_50.txt', 'fri_c0_100_10.txt',
       'fri_c0_100_25.txt', 'fri_c0_100_5.txt', 'fri_c0_100_50.txt',
       'fri_c0_250_10.txt', 'fri_c0_250_25.txt', 'fri_c0_250_50.txt',
       'fri_c0_500_10.txt', 'fri_c0_500_25.txt', 'fri_c0_500_5.txt',
       'fri_c0_500_50.txt', 'fri_c1_1000_10.txt', 'fri_c1_100_10.txt',
       'fri_c1_100_25.txt', 'fri_c1_100_5.txt', 'fri_c1_100_50.txt',
       'fri_c1_250_10.txt', 'fri_c1_250_25.txt', 'fri_c1_250_5.txt',
       'fri_c1_250_50.txt', 'fri_c1_500_10.txt', 'fri_c1_500_25.txt',
       'fri_c1_500_5.txt', 'fri_c1_500_50.txt', 'fri_c2_1000_10.txt',
       'fri_c2_1000_25.txt', 'fri_c2_1000_5.txt', 'fri_c2_1000_50.txt',
       'fri_c2_100_10.txt', 'fri_c2_100_25.txt', 'fri_c2_100_5.txt',
       'fri_c2_100_50.txt', 'fri_c2_250_10.txt', 'fri_c2_250_25.txt',
       'fri_c2_250_5.txt', 'fri_c2_250_50.txt', 'fri_c2_500_10.txt',
       'fri_c2_500_25.txt', 'fri_c2_500_5.txt', 'fri_c2_500_50.txt',
       'fri_c3_1000_10.txt', 'fri_c3_1000_25.txt', 'fri_c3_1000_5.txt',
       'fri_c3_1000_50.txt', 'fri_c3_100_10.txt', 'fri_c3_100_25.txt',
       'fri_c3_100_5.txt', 'fri_c3_100_50.txt', 'fri_c3_250_10.txt',
       'fri_c3_250_25.txt', 'fri_c3_250_5.txt', 'fri_c3_250_50.txt',
       'fri_c3_500_10.txt', 'fri_c3_500_25.txt', 'fri_c3_500_5.txt',
       'fri_c3_500_50.txt', 'fri_c4_1000_10.txt', 'fri_c4_1000_100.txt',
       'fri_c4_1000_25.txt', 'fri_c4_100_25.txt', 'fri_c4_100_50.txt',
       'fri_c4_250_10.txt', 'fri_c4_250_100.txt', 'fri_c4_250_25.txt',
       'fri_c4_250_50.txt', 'fri_c4_500_10.txt', 'fri_c4_500_100.txt',
       'fri_c4_500_25.txt', 'fri_c4_500_50.txt', 'fruitfly.txt',
       'GAMETES_Epistasis_2-Way_20atts_0.1H_EDM-1_1.txt',
       'GAMETES_Epistasis_2-Way_20atts_0.4H_EDM-1_1.txt',
       'GAMETES_Epistasis_3-Way_20atts_0.2H_EDM-1_1.txt', 'glass.txt',
       'grub-damage.txt', 'hayes-roth.txt', 'heart-c.txt', 'heart-h.txt',
       'hill-valley.txt', 'hip.txt', 'housing.txt', 'humandevel.txt',
       'hungarian.txt', 'hutsof99_child_witness.txt', 'hutsof99_logis.txt',
       'hypothyroid.txt', 'ilpd.txt', 'iris.txt', 'lsvt.txt',
       'lungcancer_GSE31210.txt', 'lupus.txt', 'lymph.txt',
       'machine_cpu.txt', 'MagicTelescope.txt', 'mbagrade.txt', 'mc1.txt',
       'mc2.txt', 'MeanWhile1.txt', 'pharynx.txt', 'PhishingWebsites.txt',
       'phoneme.txt', 'PieChart1.txt', 'PieChart2.txt', 'PieChart3.txt',
       'PieChart4.txt', 'pima.txt', 'PizzaCutter1.txt', 'PizzaCutter3.txt',
       'planning-relax.txt', 'plasma_retinol.txt', 'pm10.txt', 'pol.txt',
       'pollen.txt', 'pollution.txt', 'postoperative-patient-data.txt',
       'primary-tumor.txt', 'prnn_crabs.txt', 'prnn_fglass.txt',
       'prnn_synth.txt', 'profb.txt', 'puma32H.txt', 'puma8NH.txt',
       'pwLinear.txt', 'pyrim.txt', 'qsar-biodeg.txt', 'quake.txt',
       'qualitative-bankruptcy.txt', 'rabe_131.txt', 'rabe_148.txt',
       'rabe_166.txt', 'rabe_176.txt', 'rabe_265.txt', 'rabe_266.txt',
       'rabe_97.txt', 'ringnorm.txt', 'rmftsa_ctoarrivals.txt',
       'rmftsa_ladata.txt', 'rmftsa_sleepdata.txt', 'sa-heart.txt',
       'scene.txt', 'schizo.txt', 'schlvote.txt', 'segment.txt',
       'sensory.txt', 'servo.txt', 'sleep.txt', 'sleuth_case1102.txt',
       'sleuth_case1201.txt', 'sleuth_case1202.txt', 'sleuth_case2002.txt',
       'sleuth_ex1221.txt', 'sleuth_ex1605.txt', 'sleuth_ex1714.txt',
       'sleuth_ex2015.txt', 'sleuth_ex2016.txt', 'socmob.txt',
       'soybean.txt', 'space_ga.txt', 'SPECT.txt', 'SPECTF.txt',
       'spectrometer.txt', 'speeddating.txt', 'splice.txt', 'sponge.txt',
       'squash-stored.txt', 'squash-unstored.txt',
       'steel-plates-fault.txt', 'stock.txt', 'strikes.txt',
       'sylva_agnostic.txt', 'sylva_prior.txt', 'tae.txt']

def Get_FILES(ALL_FILES=ALL_FILES,COMPUTED_FILES=COMPUTED_FILES):
       META_FILES = [ALL_FILES[i] for i in range(len(ALL_FILES)) if
                     i not in [91, 117, 137, 144, 328, 414, 423, 279, 129, 451]]

       return [i[:-5] for i in ALL_FILES if i[:-5]+'.txt' in COMPUTED_FILES and i in META_FILES]


def Get_FILES_Cat(ALL_FILES=ALL_FILES, COMPUTED_FILES_CAT=COMPUTED_FILES_CAT):
    META_FILES = [ALL_FILES[i] for i in range(len(ALL_FILES)) if
                  i not in [91, 117, 137, 144, 328, 414, 423, 279, 129, 451]]

    return [i[:-5] for i in ALL_FILES if i[:-5] + '.txt' in COMPUTED_FILES_CAT and i in META_FILES]

space = {
    'learning_rate': hp.loguniform('learning_rate', -6., -1.),
    'n_estimators': hp.choice('n_estimators', range(20, 600)),
    'max_depth': hp.choice('max_depth', range(2, 31)),
    'min_child_weight': hp.choice('min_child_weight', range(1, 15)),
    'gamma': hp.uniform('gamma', 0.0, 10.0),
    'subsample': hp.uniform('subsample', 0.6, 1.0),
    'colsample_bytree': hp.uniform('colsample_bytree', 0.6, 1.0),
    'reg_alpha': hp.loguniform('reg_alpha', -7., 3.),
    'reg_lambda': hp.loguniform('reg_lambda', -7., 3.)}

C_range = list(range(-5,15))
gamma_range = list(range(-15,3))